version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-207-124-89.compute-1.amazonaws.com
            port: '5432'
            database: d682jheus0upnv
            ssl: true
            user: savyhiqxctyqdq
            password: ea4f33ab24a5f157ad796e5d8d8fefe0a95130ab92523ec7d84a5dcc170d9a1d
            migrations: true
